service: kmullaney-sls

useDotenv: true
configValidationMode: error

provider:
  name: aws
  region: us-west-2
  stage: cjs
  timeout: 4
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:${env:NEW_RELIC_LICENSE_KEY_SECRET}-*"
  tags:
    owner: kmullaney
    reason: example
    description: instrumentation of a cjs function
  stackTags:
    owner: kmullaney
    reason: example
    description: instrumentation of a cjs function
  environment:
    NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG
    NEW_RELIC_NATIVE_METRICS_ENABLED: false # Reduce cold start duration by not collecting VM metrics
    NEW_RELIC_EXTENSION_SEND_EXTENSION_LOGS: true # Also send extension logs

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID} # New Relic account ID
    trustedAccountKey: ${env:NEW_RELIC_TRUSTED_ACCOUNT_KEY} # New Relic account ID or parent ID
    apiKey: ${env:NEW_RELIC_USER_API_KEY} # User api key
    disableAutoSubscription: true # Don't create a subscription filter to the newrelic-log-ingestion function
    disableLicenseKeySecret: false # Use NEW_RELIC_LICENSE_KEY env var or AWS Secrets Manager secret
    enableFunctionLogs: true # Enable writing of function logs to CloudWatch
    enableExtensionLogs: true # Enable writing of extension logs to CloudWatch
    sendFunctionLogs: true # Send function logs to New Relic
    sendExtensionLogs: true # Send extension logs to New Relic
    enableIntegration: false # Don't create an api polling integration (already have Metric Streams)
    logEnabled: true # Agent logs
    logLevel: info # Agent log level
    debug: true # Serverless Framework debug
    # layerArn: arn:aws:lambda:us-west-2:451483290750:layer:NewRelicNodeJS20X:101 # pinned to bypass SSL issues

package:
  individually: true

functions:
  nodejs20x:
    description: demo commonjs instrumentation
    handler: function.handler
    runtime: nodejs20.x
    package:
      patterns:
        - "!node_modules/**"
        - "function.js"
    provisionedConcurrency: 0
    environment:
      NEW_RELIC_APP_NAME: kmullaney-sls-cjs-nodejs20x
